apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mlops
  name: flight-fastapi-env
data:
  SERVICE_ACCOUNT_JSON: '{"type": "service_account", "project_id": "mlops-final-lab", "private_key_id": "37b761b9db3414756d62c804f718ec97a030a061", "private_key": "", "client_email": "", "client_id": "", "auth_uri": "https://accounts.google.com/o/oauth2/auth", "token_uri": "https://oauth2.googleapis.com/token", "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs", "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/fast-api-app%40mlops-final-lab.iam.gserviceaccount.com", "universe_domain": "googleapis.com"}'