name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main
      - feature/google_batch

jobs:
  build-and-push:
    name: Build & Push to GCR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: gcloud auth configure-docker --quiet

      - name: Build and tag
        run: |
          docker buildx create --use
          docker buildx build \
            --tag gcr.io/${{ secrets.PROJECT_ID }}/docker-image-mlops:${{ github.sha }} \
            --tag gcr.io/${{ secrets.PROJECT_ID }}/docker-image-mlops:latest \
            . --load

      - name: Push image to GCR
        run: |
          docker push gcr.io/${{ secrets.PROJECT_ID }}/docker-image-mlops:${{ github.sha }}
          docker push gcr.io/${{ secrets.PROJECT_ID }}/docker-image-mlops:latest

  trigger-batch:
    needs: [build-and-push]
    name: Trigger Google Cloud Batch Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Trigger Batch Job
        run: |
          gcloud batch jobs submit job-name \
            --location=us-central1 \
            --service-account=SERVICE_ACCOUNT_EMAIL \
            --command="docker run -v $(pwd):/app gcr.io/${{ secrets.PROJECT_ID }}/docker-image-mlops:latest"
