name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main
      - feature/google_batch

env:
  SHORT_SHA: ${{ github.sha }}
  IMAGE_TAG: docker-image-mlops:tag
  PROJECT_ID: mlops-final-lab
  REGION: us-central1
  GCR_LOCATION: gcr.io/${{ env.PROJECT_ID }}

jobs:
  build-and-push:
    name: Build & Push to GCR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.GCR_LOCATION }} --quiet

      - name: Build and tag
        run: |
          docker buildx create --use
          docker buildx build \
            --tag ${{ env.GCR_LOCATION }}/docker-image-mlops:${{ env.IMAGE_TAG }} \
            --tag ${{ env.GCR_LOCATION }}/docker-image-mlops:${{ env.IMAGE_TAG }}_${{ env.SHORT_SHA }} \
            . --load

      - name: Push image to GCR
        run: |
          docker push ${{ env.GCR_LOCATION }}/docker-image-mlops:${{ env.IMAGE_TAG }}
          docker push ${{ env.GCR_LOCATION }}/docker-image-mlops:${{ env.IMAGE_TAG }}_${{ env.SHORT_SHA }}

  trigger-batch:
    needs: [build-and-push]
    name: Trigger Google Cloud Batch Job
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info